"""make_category_and_image_nullable

Revision ID: 4b9629994762
Revises: 6f14914e7dfc
Create Date: 2025-10-19 12:28:08.522533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9629994762'
down_revision: Union[str, Sequence[str], None] = '6f14914e7dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'image_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
