"""make_address_id_nullable

Revision ID: 6f14914e7dfc
Revises: aa3365df75ca
Create Date: 2025-10-14 15:28:11.138019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f14914e7dfc'
down_revision: Union[str, Sequence[str], None] = 'aa3365df75ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'address_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'address_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
