"""make_supplier_address_nullable

Revision ID: e9c9441ac847
Revises: 4b9629994762
Create Date: 2025-10-20 15:27:56.864898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c9441ac847'
down_revision: Union[str, Sequence[str], None] = '4b9629994762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'address_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'address_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
