"""add_filename_to_image_model

Revision ID: fd8c0a3b9f29
Revises: e9c9441ac847
Create Date: 2025-10-21 22:48:56.346427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8c0a3b9f29'
down_revision: Union[str, Sequence[str], None] = 'e9c9441ac847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('filename', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'filename')
    # ### end Alembic commands ###
